[tool.black]
line-length = 120

[tool.ruff]
select = ["E", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
]
per-file-ignores = {}
line-length = 120